### ISSUE TITLE
Finalize Jenkins build/release/IVT pipeline

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#205]

**Comment by scottkurz** [comment]
By EOY this will be:

**Comment by scottkurz** [comment]
@awisniew90 can you please summarize where we left off for this release?  Thanks.

**Comment by awisniew90** [comment]
For this release, the "liberty-tools-eclipse-release" Jenkins pipeline will:

1. Build the latest code in our repo
2. Sign the jar files using the cert-sign tool in GSA
3. Use the tycho plugin to recalculate the hashes for the signed jars
4. Output the signed repository and zip to be manually downloaded and then uploaded to DHE

There is a basic "install" of the plugin into eclipse, but this succeeds whether or not the jars are signed

For the next rev of this pipeline, we need to:

1. Add verification that the user will not be prompted to approve unsigned code when installing
2. Add SWTbot (or similar) functional testing

**Comment by scottkurz** [comment]
Thx @awisniew90
