### ISSUE TITLE
zsh shell on mac liberty:dev fails to start through Liberty dashboard with Maven wrapper

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-eclipse#230]
Generated a wrapper with maven wrapper 3.1.1. plugin. On Mac, zsh shell. 

Error seems to be coming from this line in the wrapper script:
`MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"`

Added to the top of the wrapper script:
```
set -x
 MVNW_VERBOSE=true
```

When running through the Liberty dashboard:

```
/Library/Java/JavaVirtualMachines/jdk-17.0.4.1+1/Contents/Home/bin/java '  ' -classpath /Users/kathrynkodama/devex/sampleProjects/demo-devmode/.mvn/wrapper/maven-wrapper.jar '-Dmaven.multiModuleProjectDirectory=/Users/kathrynkodama/devex/sampleProjects/demo-devmode' org.apache.maven.wrapper.MavenWrapperMain io.openliberty.tools:liberty-maven-plugin:dev -f /Users/kathrynkodama/devex/sampleProjects/demo-devmode
```

But when running `./mvw liberty:dev` on terminal:
```
/Library/Java/JavaVirtualMachines/jdk-17.0.4.1+1/Contents/Home/bin/java  -classpath /Users/kathrynkodama/devex/sampleProjects/demo-devmode/.mvn/wrapper/maven-wrapper.jar '-Dmaven.multiModuleProjectDirectory=/Users/kathrynkodama/devex/sampleProjects/demo-devmode' org.apache.maven.wrapper.MavenWrapperMain io.openliberty.tools:liberty-maven-plugin:dev -f /Users/kathrynkodama/devex/sampleProjects/demo-devmode
```

Workaround was to create a jvm.options file with any value, and now Start works through the Liberty dashboard:
Created ./mvn/jvm.config:
```
-Dx=y
```

Now running through dashboard, start works as expected. Command resolves to: 
```
/Library/Java/JavaVirtualMachines/jdk-17.0.4.1+1/Contents/Home/bin/java '-Dx=y  ' -classpath /Users/kathrynkodama/devex/sampleProjects/demo-devmode/.mvn/wrapper/maven-wrapper.jar '-Dmaven.multiModuleProjectDirectory=/Users/kathrynkodama/devex/sampleProjects/demo-devmode' org.apache.maven.wrapper.MavenWrapperMain io.openliberty.tools:liberty-maven-plugin:dev -f /Users/kathrynkodama/devex/sampleProjects/demo-devmode
```

**Comment by scottkurz** [comment]
Thx Kathryn for capturing so much detail.  I'm adding my incomplete notes.

* Reading doc it seems this issue intersects the difference btw bash and zsh
* In reading doc I see that bash creates will substitue ' ' for a quoted empty var, but nothing for unquoted empty var substitution
* In reading doc I see claims that zsh seems to use ' ' even for unquoted empty var substitution
* When running via Liberty Tools we do indeed seem to see ' ' for the unquoted empty var substitution in `mvnw`
* However, running the same `mvnw` from a regular shell (outside Liberty Tools) on Mac seems to result in the bash behavior, i.e. nothing for an  unquoted empty var substitution.

It seems there must be some shell option which is set in a "normal" zsh Mac session that's not set when we run via the Liberty Tools terminal.

**Comment by scottkurz** [comment]
I recreated the issue outside of Liberty Tools on Ubuntu 20.04.3 LTS, (with whatever bash and zsh versions I had there).   I'd like to try to build a Docker recreate script and then open a JIRA.

I'm thinking we could try a workaround of setting the MAVEN_OPTS env var in the mvnw case to something Liberty-specific, a placeholder value just to avoid an empty value, e.g. 

`MAVEN_OPTS=$MAVEN_OPTS:-Dio.openliberty.tools.eclipse.mvnwrapper=true`

**Comment by scottkurz** [comment]
Besides the problem here, should we also spend some time trying again the older wrapper?

**Comment by scottkurz** [comment]
Opened issue on mvnw:  https://issues.apache.org/jira/browse/MWRAPPER-83
