### ISSUE TITLE
Can't move to latest jdt ls plugin because of cyclic de-referencing errors when loading the latest jdt ls plugin

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-tools-eclipse#243]
JDT-LS issue https://github.com/eclipse/eclipse.jdt.ls/issues/2309 addresses this. We will move to the latest once it has been fixed.

Current plan is to start at JDT-LS 1.5.0 for now

**Comment by scottkurz** [comment]
I think we're past this now.
