### ISSUE TITLE
SVT: Language servers assistance not available in XML editor 

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/liberty-tools-eclipse#282]
I am trying to consume liberty tools 0.5.0 version on eclipse 2022-09-R release. When I try to edit server.xml in xml editor then I did not get language server assistance in the XML editor. I do get assistance when I open the file in Generic Text Editor.

XML Editor
![image](https://user-images.githubusercontent.com/713849/205992584-11b390e8-a91c-4e6f-8321-d9c6ce6609c0.png)

Generic Text Editor
![image](https://user-images.githubusercontent.com/713849/205992932-e8256929-4536-49f5-bf19-8b7a7f9e683a.png)

**Comment by scottkurz** [comment]
We did mention this as a limitation in the UFO design.   For server.xml, the file is bound to the Generic Text Editor by default.   

It might make more sense to try to do a more thorough binding to the Generic Text Editor than to enable the function in the XML Editor.

I'm guessing there wasn't a real need or desire to use the XML Editor @jagraj ?  But it's just a case where this was the default editor opening a file on double-click?

**Comment by scottkurz** [comment]
I don't think we have any plans to address this in the near-term.  Closing for now.
