### ISSUE TITLE
Doc updates

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#307]
See running list at:  https://ibm.box.com/s/ufu12i1syix5n52d76g6k618m69qo9l2
(Apologies, this is an IBM-only link but the PR will obviously be open source)

**Comment by kathrynkodama** [comment]
PRs from the ID review for Liberty Tools for IntelliJ:
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/221
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/236
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/235
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/234
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/233
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/232

**Comment by scottkurz** [comment]
Moving milestone

**Comment by scottkurz** [comment]
Good for this round.
