### ISSUE TITLE
For snippet code gen via MP LS, fix template variables getting written into Java w/o substitution

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-tools-eclipse#31]
When inserting snippet code via the MP LS snippet support, well known LS template vars supported by the MP LS in snippet code are not resolved and appear as is in the generated snippet code.  These vars need to be resolved (probably via the underlying LS 4 Eclipse (LS4E) layer.

example - this liveness snippet insert:

```package com.example.demo.ls.mpcfg.health;

import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.HealthCheckResponse;
import org.eclipse.microprofile.health.Liveness;

import javax.enterprise.context.ApplicationScoped;

@Liveness
@ApplicationScoped
public class ${TM_FILENAME_BASE} implements HealthCheck {

	@Override
	public HealthCheckResponse call() {
		return HealthCheckResponse.named(${TM_FILENAME_BASE}.class.getSimpleName()).withData("live",true).up().build();
	}
}
```

`${TM_FILENAME_BASE}` is a LS template var that should be resolved to a value when inserted.

**Comment by scottkurz** [comment]
I think we've resolved this right @mezarin ?  Closing assuming so.

**Comment by mezarin** [comment]
I think so. LSP4E fixed the issue and it is now in eclipse 2022-09, which we now have as a pre-req.
