### ISSUE TITLE
Do we have a release plan to support JakartaEE 10 & Microprofile 6.0

### ISSUE THREAD

**Issue by RuiBaiXYZ** [OpenLiberty/liberty-tools-eclipse#356]
Do we have a release plan , eg. v0.9.0, making the alignment to Open Liberty Release 23.0.0.3 .
espcially for supporting Jakarta EE 10 and Microprofile 6.0 in Eclipse IDE

**Comment by scottkurz** [comment]
> Do we have a release plan , eg. v0.9.0, making the alignment to Open Liberty Release 23.0.0.3 . espcially for supporting Jakarta EE 10 and Microprofile 6.0 in Eclipse IDE

Hi.   Thanks for your interest.

The short answer is that we don't have a target date and it will take some time.

For a longer answer, let me note that support for Jakarta and MicroProfile APIs will be provided by the [LSP4Jakarta](https://github.com/eclipse/lsp4jakarta) and [LSP4MP](https://github.com/eclipse/lsp4mp) projects which we will integrate into Liberty Tools Eclipse. 

The LSP4Jakarta project has support for Jakarta 9+ APIs (the **jakarta.*** pkg namespace).   There is not currently a target for full support for every EE 9/9.1/10 API, but you could certainly use it with the set of function it does provide today, against an EE10 runtime.   

The latest release of LSP4MP (0.7.0) targets support for (the **jakarta.*** pkg namespace), though there too, work for all the individual features within MicroProfile 6 is still ongoing.  

The Liberty Tools Eclipse tooling can generally be used with any supported version of Open Liberty (naturally there is no point in running against an older runtime version that doesn't support the API and feature versions your app is using).

The next priorities are to integrate the latest LSP4MP release on a base of a recent Eclipse release.  We are working on this now but don't have a target date for yet.

**Comment by RuiBaiXYZ** [comment]
Got it.
Thanks for your detailed explanation.
