### ISSUE TITLE
SVT:No pop-ups while hovering over features in server.xml when I install the ACME ee10 application

### ISSUE THREAD

**Issue by rumanaHaque** [OpenLiberty/liberty-tools-eclipse#373]
Installed Eclipse 2023-03, and installed Liberty Tools for Eclipse.

Got the acme-ee10 application from this repo -  https://github.ibm.com/was-svt/acme-ee/tree/acme-ee10-latest-db2jars, and imported it as an existing Maven project in Eclipse.

I have a server.xml file in a separate directory (not within a project) - called config.

<img width="1046" alt="image" src="https://github.com/OpenLiberty/liberty-tools-eclipse/assets/31224827/b8d1584b-f139-404a-a109-012ad3cdadea">

When I hover over any of the features in the server.xml, I don't see any pop-ups.

<img width="643" alt="image" src="https://github.com/OpenLiberty/liberty-tools-eclipse/assets/31224827/5eaf833c-2f18-4ac6-8499-b0b5dd538719">

**Comment by cherylking** [comment]
The Liberty Config Language Server only provides assistance for server.xml files located in `src/main/liberty/config`.

**Comment by rumanaHaque** [comment]
Even when I copied over the server.xml file to src/main/liberty/config dir, I still cannot get any hover for any of the elements in server.xml.

However, in the same machine, (same Eclipse and jdk), I created a new workspace, and created a starter application using the https://openliberty.io/start/  url.
When I opened the server.xml in that workspace, I was able to get the hover for the features.

So this seems to happen specifically for the acme-ee10 app.

**Comment by scottkurz** [comment]
@rumanaHaque let's start down the path of trying to get diagnostics... can you please first grab the Lemminx LS log that you'd enable via:

**Comment by scottkurz** [comment]
My mental model about what's going on is that the Lemminx server is failing to complete initialization, rather than there being a more subtle bug once the LS extension logic is being executed.   

That's not to say that there's no way it could be an issue with the LCLS xml ext code, but I think it's an initialization-type problem based on recreating it (intermittently) myself.

**Comment by rumanaHaque** [comment]
Here's the LemMinX language server logs as you requested.

[languageServers-log.zip](https://github.com/OpenLiberty/liberty-tools-eclipse/files/11457146/languageServers-log.zip)

**Comment by rumanaHaque** [comment]
I still see this using the latest Eclipse driver - io.openliberty.tools.eclipse-0.9.1.202305311908-repository.zip.

I still cannot hover over any of the features/elements in the server.xml to get a pop-up.

**Comment by scottkurz** [comment]
A bit of a slow response, I know.. but looking at the XML LS logs, we have:  

> [2023-05-11T17:19:47.142821700-07:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
> {"jsonrpc":"2.0","id":"37","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///C:/eclipse-workspace/acme-ee10/acme-ee/AcmeWebEjbEar/src/main/liberty/config/server.xml"},"position":{"line":23,"character":10}}}
> [2023-05-11T17:19:48.153114500-07:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
> Content-Length: 240
> ...
> 
> {"jsonrpc":"2.0","id":"37","result":{"contents":{"kind":"markdown","value":"Configuration properties for an HTTP endpoint.\r\n\r\nSource: [ol-23.0.0.4.xsd](file:/C:/eclipse-workspace/acme-ee10/acme-ee/AcmeWebEjbEar/target/.libertyls/ol-23.0.0.4.xsd)"},"range":{"start":{"line":23,"character":5},"end":{"line":23,"character":17}}}}

So there is a gap of about 3 seconds.   The timeout in `org.eclipse.lsp4e.operations.hover.LSPTextHover` is 1s.

TODO:  look to understand better why there's such a slowdown.

**Comment by scottkurz** [comment]
Let's dup this to https://github.com/OpenLiberty/liberty-tools-eclipse/issues/134.

We have more debug instructions there, more captured logs, and now the only concern left within that issue is hover
