### ISSUE TITLE
SVT: Server.xml pop-ups giving xml header

### ISSUE THREAD

**Issue by danielguinan1** [OpenLiberty/liberty-tools-eclipse#379]
When hovering over any part of the server.xml I get the description buried inside the xml code.
<img width="584" alt="Screenshot 2023-05-16 at 12 58 55 PM" src="https://github.com/OpenLiberty/liberty-tools-eclipse/assets/51483278/75a65793-b969-492d-8125-2007477a4024">

This environment is on RHEL 9 with the latest eclipse and bundled java.

Here is the server.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<server>
  <!-- Enable features -->
  <featureManager>
    <feature>microProfile-5.0</feature>
  </featureManager>

  <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
  <httpEndpoint 
    id="defaultHttpEndpoint" 
    host="*" 
    httpPort="9080" 
    httpsPort="9443">
    <accessLogging 
      enabled="${ACCESS_LOGGING_ENABLED}" 
      filepath="${server.output.dir}/logs/http_defaultEndpoint_access.log" 
      logFormat='%h %u %t "%r" %s %b %D %{User-agent}i'>
    </accessLogging>
  </httpEndpoint>

  <quickStartSecurity userName="${env.USERNAME}" userPassword="${env.PASSWORD}" />

  <logging 
    consoleFormat="${LOGGING_FORMAT}" 
    consoleSource="message,trace,accessLog,ffdc,audit" 
    messageFormat="${LOGGING_FORMAT}" 
    messageSource="message,trace,accessLog,ffdc,audit" 
    traceSpecification="${TRACE_SPEC}" />

  <webApplication name="acmeair-mainservice" location="acmeair-mainservice-java-5.0.war" contextRoot="/acmeair">
    <!-- enable visibility to third party apis -->
    <classloader apiTypeVisibility="api,ibm-api,spec,stable,third-party" />
  </webApplication>

  <cors 
    domain="/acmeair" 
    allowedOrigins="*" 
    allowedMethods="OPTIONS, GET, DELETE, POST" 
    allowedHeaders="*" 
    allowCredentials="true" 
    maxAge="3600" />

</server>
```
[org.eclipse.wildwebdeveloper.xml.log](https://github.com/OpenLiberty/liberty-tools-eclipse/files/11499491/org.eclipse.wildwebdeveloper.xml.log)
Lemminx log

**Comment by danielguinan1** [comment]
<img width="1004" alt="Screenshot 2023-06-07 at 11 33 24 AM" src="https://github.com/OpenLiberty/liberty-tools-eclipse/assets/51483278/de98c57c-e439-40cd-8897-2bce6569b5d8">
After updating to the latest driver (6/5) I'm no longer encountering this issue.  @scottkurz Were there any changes made regarding this issue?

**Comment by scottkurz** [comment]
> After updating to the latest driver (6/5) I'm no longer encountering this issue. @scottkurz Were there any changes made regarding this issue? 

No...didn't know what was happening before, not sure now why it stopped either.

**Comment by scottkurz** [comment]
I'm not sure this is recreatable at this point.  I wonder if it could have been the fault of another LSP-related layer in Eclipse.  Closing but please re-open as needed.
