### ISSUE TITLE
Cannot start servers due to port conflict, even though ports are unique

### ISSUE THREAD

**Issue by l3ender** [OpenLiberty/liberty-tools-eclipse#413]
We are unable to use the Servers view in Eclipse to start servers which have different ports, specified by overriding the desired ports in an individual server's environment file.

An example of the Liberty server.xml config is:

```xml
<server description="test1">
    <featureManager>
        <feature>servlet-3.1</feature>
        <feature>localConnector-1.0</feature>
    </featureManager>

    <variable defaultValue="9080" name="HTTP_PORT"/>
    <variable defaultValue="9443" name="HTTPS_PORT"/>
    <httpEndpoint host="*" httpPort="${HTTP_PORT}" httpsPort="${HTTPS_PORT}" id="defaultHttpEndpoint"/>
</server>
```

We then override the ports for a particular instance of a server using its server.env file:

```
HTTP_PORT=9081
HTTPS_PORT=9444
```

However, if a server is started with the default config (no environment override), subsequent servers cannot start even when the ports use unique values. Eclipse appears to only be aware of the ports in server.xml and not in server.env:

> Several ports (9080, 9443) required by test-server-2 are already in use. The server might be running in another process, or a system process might be using the port. To start this server you will need to stop the other process or change the port numbers.

![image](https://github.com/OpenLiberty/liberty-tools-eclipse/assets/2243641/2c06ff77-be2a-4586-be82-895634bc3b37)

I confirmed the above is possible when starting servers with the liberty command line, so it appears to be a bug in the IDE plugin.

Please let me know if I can provide any other info--thanks!

**Comment by scottkurz** [comment]
The Liberty Tools Eclipse feature doesn't itself integrate with the "Servers" view (nor does it really integrate with WTP more generally).   The behavior you're seeing is likely coming from one of the earlier Liberty Developer Tools or WebSphere Developer Tools features. 

Let me try to find someone to comment on this issue and route it accordingly.

**Comment by scottkurz** [comment]
(Closed the issue to show that it's not relevant to this repo, but I'm still going to make sure we follow-up).

**Comment by scottkurz** [comment]
@l3ender I'd suggest opening an [issue](https://github.com/OpenLiberty/open-liberty-tools/issues/new) on Open Liberty Tools.   Thanks.
