### ISSUE TITLE
Installation error for Eclipse with OpenJDK (OpenJ9)

### ISSUE THREAD

**Issue by RuiBaiXYZ** [OpenLiberty/liberty-tools-eclipse#427]
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.justj.openjdk.hotspot.jre.full,17.0.8.v20230801-1951
No repository found containing: osgi.bundle,org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64,17.0.8.v20230801-1951

JDK Info
$ java --version
java 17.0.7 2023-04-18
IBM Semeru Runtime Certified Edition 17.0.7.0 (build 17.0.7+7)
Eclipse OpenJ9 VM 17.0.7.0 (build openj9-0.38.0, JRE 17 Linux amd64-64-Bit Compressed References 20230418_417 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 7a1e0864e99 based on jdk-17.0.7+7)

**Comment by scottkurz** [comment]
Thank you for reporting the issue.  

So you're running on Linux and getting this error when installing Liberty Tools Eclipse?

Can you share more details about your installation?   It looks like the "Enterprise Java and Web Developers" package.  Was this for Eclipse 2023-03 release (v4.27)?

Could you share your installation details by doing:
**Help -> About Eclipse IDE -> Installation Details**
then selecting, copying, and paste the first tab?

**Comment by scottkurz** [comment]
FWIW, I just installed:

* Eclipse 2023-03 release (v4.27) "Enterprise Java and Web Developers" package
* IBM Semeru Runtime Open Edition 17.0.7.0 (build 17.0.7+7)     (matches the certified edition version above)
* on top of Ubuntu 22.04.2 via WSL
* Liberty Tools Eclipse v23.0.7

Everything seemed to install and run fine.

**Comment by scottkurz** [comment]
Closing for now, please re-open with the requested info if you need to.  Thank you.
