### ISSUE TITLE
SVT:Adding a feature removes the some text next to it.

### ISSUE THREAD

**Issue by rumanaHaque** [OpenLiberty/liberty-tools-eclipse#470]
I am testing the ACME app using LT in Eclipse (Windows env).
When I go to the server.xml, and add
<fe Ctrl+Space - I see this added `<feature></feature>`

Next I do app in the space between the features
`<feature>app</feature`>

If I do Ctrl+Space after typing app, I see one of the suggestions is appSecurityClient-1.0 feature.
If I select that, it adds the feature, but removes the "</" next to it, and shows up as an error.

 
<img width="677" alt="image" src="https://github.com/OpenLiberty/liberty-tools-eclipse/assets/31224827/d1141fc2-274c-4fa7-b7d7-ed3cfe25483d">

**Comment by scottkurz** [comment]
I just tried variations of this 10 times and recreated the problem once !   When I recreated it, it was the very last child element under `<featureManager>` but it didn't happen consistently even in the last position.   Will have to think what the next step would be.

**Comment by scottkurz** [comment]
This is going to take some time to debug.  The workaround is simply adding back the text (though that's annoying).  Moving to next milestone.

**Comment by scottkurz** [comment]
I think we can close this as dup of #405 .   Thx @cherylking.  I was just combing through the backlog myself and noticed the same thing.

**Comment by rumanaHaque** [comment]
Yes - sorry I too realized that 405 and 470 are duplicates.
