### ISSUE TITLE
Includes Liberty/OpenLiberty Server Adapters directly

### ISSUE THREAD

**Issue by hantsy** [OpenLiberty/liberty-tools-eclipse#481]
After I installed Liberty Tools from Eclipse Marketplace, and then I want to add an OpenLiberty server instance in the **Servers** view.

In the Add server dialog, when selecting *IBM*, there is no Openliberty server/Liberty server items avaiable, click the Install Webshpere liberty Extended tools, it will take long time to install the adapters related libs into my Eclipse. 

Yesterday, it took tow hours but was still installing status, I had to give up. Today I tried again, it took several hours to install, and still in progress. The experience is terrifying for me.

Why not like other Server adapters, such as JBoss/Wildfly, Glassfish etc, provides the server items in the add server dialog directly.

**Comment by hantsy** [comment]
If there are some license issue, please add open-sourced Openliberty support as first citizen, label it as `OpenLiberty` in the **Add server** category. 

Move the commercial WebSphere products support to another IBM labeled plugin.

**Comment by scottkurz** [comment]
There's also the fact that the "facets" for newer EE levels are not, to my knowledge, yet provided by the WTP project.  So the "Publish" operations using these facets would have issues using a WTP Server approach.    If you're mainly intending to use the older EE levels (8 and below), you can use Liberty Developer Tools (linked above).

**Comment by scottkurz** [comment]
Not planning to do anything here for the time being.  Please continue to provide your feedback, and thanks for raising the question.
