### ISSUE TITLE
Unable to read repository at https://public.dhe.ibm.com/...  Failed to respond

### ISSUE THREAD

**Issue by vickimfox** [OpenLiberty/liberty-tools-eclipse#506]
## Summary

Attempt to install or update Liberty Tools via _Marketplace_ or _Install New Software_ fails with **Skipping update check for repository ... failed to read**.

This behavior started happening between start of March and now (end of March).

## Details

Around first week of March, the auto update of my Eclipse IDE updated Liberty Tools to the 24.0.0.3 release. There were no problems.

Around last week of March, I was editing a Jakarta EE program, specifically the `microprofile-config.properties` file. I was receiving pop-up dialogs reporting errors from the LCLS and unable to resolve properties. I decided to remove Liberty Tools and re-install. I am looking into moving the location of the properties file because I suspect the LCLS/Properties component is looking in different directories. NOTE: I'm **not reporting** the properties problem in this issue, I'm **reporting** repository access problem.

I was able to reinstall Liberty Tools 24.0.3 by downloading the ZIP file from the GitHub Releases and installing from the Archive (ZIP).

## Configuration

- Eclipse Build = 4.31.0.I20240229-0520
- Java Version = 17.0.10
- Java Vendor = Eclipse Adoptium
- BootLoader = OS=win32 (Windows 10), ARCH=x86_64, WS=win32, NL=en_US
- Framework = package.jee

The workstation is within a corporate network.

- Proxy = ZScaler for Govt
- Certs = Java default plus Corporate. Corporate used on internal network from Proxy

## Research

After receiving the first error from Marketplace, I double-checked the proxy and certs configuration. There were no changes.

With Marketplace failing, I then tried to use Install Software directly against `dhe.ibm.com` registry. This failed with same error.

I then tried using `curl` from command line. This failed with same error.

I contacted the corporate network administrator on-call. He reported "not seeing any blocks in the proxy logs".

I tried the install operation on my personal computer at home. It worked with no problems.

This leads me to think there is something going on between the corporate proxy (ZScaler for Govt) and the IBM registry.

## Event Details from Eclipse

```
Skipping update check for repository 'https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/liberty-tools-eclipse/24.0.3/repository/' - failed to read repository. Affected entries:

org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/liberty-tools-eclipse/24.0.3/repository/artifacts.xml.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:250)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.getLocalFile(SimpleArtifactRepositoryFactory.java:68)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:92)

Caused by: org.apache.hc.core5.http.NoHttpResponseException: public.dhe.ibm.com:443 failed to respond
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:301)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
```

**Comment by vickimfox** [comment]
The network administrator remembered seeing this problem with another branch of the dhe.ibm.com domain. It is due to an issue with SSL decryption from dhe.ibm.com detected by the ZScaler proxy service. The fix is to add a rule to ZScaler to ignore the SSL decryption.

**Comment by scottkurz** [comment]
@vickimfox thank you for opening the issue.  Have been following-up with the team managing DHE, but don't have any updates.  Still, wanted to acknowledge this in the meantime.

**Comment by vickimfox** [comment]
@scottkurz 
The network administrator turned off SSL decryption in the ZScaler proxy for the dhe.ibm.com URL. 
This fixed the problem. I am able to pull code via Maven, Eclipse IDE, or command-line.
The administrator suspects the problem may be related with IBM hosting change from dhe to southdata.ibm.com.

Feel free to close this issue.

**Comment by scottkurz** [comment]
Great...thank you for the update.  Glad the problem is resolved and will pass this along to the DHE team.
