### ISSUE TITLE
Update reference to NOTICES in feature.xml

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#509]
In `features/io.openliberty.tools.eclipse.feature/feature.properties` it still links to:

> For additional license information see: https://raw.githubusercontent.com/OpenLiberty/liberty-tools-eclipse/liberty-tools-23.0.1/NOTICES \n\

**Comment by scottkurz** [comment]
Maybe we could say something that won't go stale, like:"see the NOTICES file in the repo at the corresponding source version, the most recent version of which is at https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/NOTICES"

**Comment by awisniew90** [comment]
Fixed by PR #513
