### ISSUE TITLE
Update JDT LS; Support Eclipse IDE 2024-06 and Java 21

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/liberty-tools-eclipse#510]
Ref https://github.com/eclipse-packaging/packages/blob/master/CHANGELOG.md, Eclipse IDE 2024-06 ships with Java 21 by default and "many downloads now require Java 21".

Filing this issue to track corresponding support and update for this Eclipse IDE release and Java 21.

**Comment by scottkurz** [comment]
We can close this when we update jdt.ls

**Comment by awisniew90** [comment]
JDTLS Updated to 1.39

**Comment by awisniew90** [comment]
PR https://github.com/OpenLiberty/liberty-tools-eclipse/pull/519
