### ISSUE TITLE
Intermittent timeout failures in GHA Windows build

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/liberty-tools-eclipse#93]
The Windows build in GHA is intermittently failing with timeouts. This affects both the Gradle and Maven tests and "testStart", "testStartWithParms" and "testRunTests" methods.

**Comment by scottkurz** [comment]
I'm working on a change to test for the server being stopped before continuing to the next test.  This issue doesn't have enough detail and is old so closing, however.
